name: ${project.name}
version: ${project.version}
author: CuzIm1Tigaaa
depend:
  - ProtocolLib
main: de.cuzim1tigaaa.spectate.Main
commands:
  spectate:
    aliases: [spec]
    usage: /spectate [target]
  spectatelist:
    aliases: [speclist]
    usage: /spectatelist
  spectatecycle:
    aliases: [speccycle]
    usage: /spectatecycle <start|stop> ...
  spectatehere:
    aliases: [spechere,spech]
    usage: /spectatehere
  spectatereload:
    aliases: [specreload,specrl]
    usage: /spectatereload
  unspectate:
    aliases: [unspec]
    usage: /unspectate <Player|all> [true|false]
permissions:
  spectate.*:
    default: op
    children:
      spectate.admin: true
      spectate.use.*: true
      spectate.utils.*: true
      spectate.bypass: false
  spectate.use.*:
    default: false
    children:
      spectate.use: true
      spectate.use.here: true
      spectate.use.others: true
      spectate.use.cycle: true
      spectate.list: true
      spectate.useonly.cycle: false
  spectate.utils.*:
    default: false
    children:
      spectate.inventory: true
      spectate.tab: true
  spectate.bypass.*:
    default: false
    children:
      spectate.tablist: true
      spectate.cannot: true
  spectate.admin:
    default: false
    children:
      spectate.reload: true
      spectate.unspectate: true